// ============================================================
// AgriOS — Demo Data (pre-seeded, realistic, clearly labeled)
// Used when external APIs are unavailable
// ============================================================
import type { WeatherData, SoilProfile, SatelliteSnapshot, FarmAlert, RegenerativeScore, Farm, AIRecommendation } from '@/types';

export const DEMO_FARM_ID = 'demo-farm-001';

// The canonical demo farm used across the app when no live farm exists yet.
export const DEMO_FARM: Farm = {
  id: DEMO_FARM_ID,
  ownerId: 'demo-user',
  name: 'Demo Farm',
  location: {
    lat: 26.85,
    lng: 80.95,
    address: 'Kumar Farm, Chinhat',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'India',
  },
  areaHa: 2.4,
  crop: 'Wheat',
  cropVariety: 'HD-3086',
  cropStage: 'vegetative',
  plantingDate: '2026-08-10',
  irrigationType: 'drip',
  farmingPractice: 'conventional',
  createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  updatedAt: new Date().toISOString(),
};

// Demo AI advisory used when Gemini is not configured.
export const DEMO_RECOMMENDATION: AIRecommendation = {
  summary: 'Your wheat field in Lucknow shows stable vegetation signal (NDVI 0.58) but elevated humidity (72%) creates moderate disease risk. Rainfall of 8-12mm is expected in 36-48 hours — delay irrigation. Inspect lower leaves tomorrow morning for early fungal symptoms.',
  riskLevel: 'medium',
  confidence: 81,
  evidence: [
    { source: 'weather', finding: 'Humidity 72% — above 70% disease risk threshold', value: 72 },
    { source: 'satellite', finding: 'NDVI 0.58 — within normal range for vegetative stage', value: 0.58 },
    { source: 'weather', finding: '8mm rainfall forecast in 36-48 hours', value: 8 },
    { source: 'soil', finding: 'pH 7.8 — slightly alkaline, may reduce micronutrient availability', value: 7.8 },
    { source: 'crop_stage', finding: 'Vegetative stage — dense canopy creates favorable disease microclimate' },
  ],
  observations: [
    'Vegetation signal is stable and within normal range for this growth stage',
    'High relative humidity creating disease-favorable conditions',
    'Significant rainfall forecast — irrigation delay recommended',
    'Soil pH slightly alkaline — monitor for iron/manganese deficiency symptoms',
  ],
  recommendations: [
    'Delay irrigation by 24-36 hours pending rainfall assessment',
    'Inspect lower canopy for early fungal disease symptoms tomorrow morning',
    'Monitor drainage after rainfall to prevent waterlogging in low-lying areas',
    'Consider foliar micronutrient application if yellowing observed',
  ],
  actionsToday: [
    { action: 'Inspect 15-20 representative plants for fungal symptoms', reason: 'High humidity + moderate temperature = disease-favorable conditions', urgency: 'today', effort: 'low' },
    { action: 'Check and clear field drainage channels', reason: '8-12mm rainfall expected — prevent waterlogging', urgency: 'today', effort: 'low' },
  ],
  actionsThisWeek: [
    { action: 'Reassess irrigation schedule after rainfall settles', reason: 'Avoid over-irrigation and nutrient leaching', urgency: 'this_week', effort: 'low' },
    { action: 'Monitor NDVI trend — check again in 7 days', reason: 'Rainfall should improve vegetation signal if crop is healthy', urgency: 'this_week', effort: 'low' },
    { action: 'Test soil for micronutrient status if yellowing appears', reason: 'Alkaline pH can lock out iron, zinc, manganese', urgency: 'this_week', effort: 'medium' },
  ],
  regenerativeActions: [
    { action: 'Plan cover crop for post-harvest soil protection', reason: 'Organic carbon (0.48 g/kg) is low — cover crops rebuild soil biology', urgency: 'this_month', effort: 'medium' },
    { action: 'Source organic compost for end-of-season application', reason: 'Long-term soil pH correction and organic matter improvement', urgency: 'this_month', effort: 'medium' },
  ],
  warnings: ['AI-generated advisory — verify recommendations in field before major decisions', 'Disease risk elevated — do not delay inspection'],
  needsFieldVerification: true,
  dataSources: ['Open-Meteo weather (no API key)', 'SoilGrids soil data', 'Sentinel-2 via Google Earth Engine', 'Gemini 2.0 Flash'],
  disclaimer: 'AI-assisted agricultural assessment. Not a replacement for qualified agronomic advice. Field verification recommended for all major decisions.',
  generatedAt: new Date().toISOString(),
};

export const DEMO_WEATHER: WeatherData = {
  current: {
    temperature: 31,
    apparentTemperature: 34,
    humidity: 72,
    precipitation: 0,
    windSpeed: 12,
    weatherCode: 2,
    description: 'Partly cloudy',
  },
  forecast: [
    { date: '2026-09-03', maxTemp: 32, minTemp: 22, precipitation: 0, precipitationProbability: 10, humidity: 68, weatherCode: 1, description: 'Mainly clear' },
    { date: '2026-09-04', maxTemp: 29, minTemp: 21, precipitation: 8, precipitationProbability: 70, humidity: 80, weatherCode: 63, description: 'Moderate rain' },
    { date: '2026-09-05', maxTemp: 27, minTemp: 20, precipitation: 12, precipitationProbability: 85, humidity: 85, weatherCode: 63, description: 'Moderate rain' },
    { date: '2026-09-06', maxTemp: 28, minTemp: 21, precipitation: 2, precipitationProbability: 30, humidity: 75, weatherCode: 2, description: 'Partly cloudy' },
    { date: '2026-09-07', maxTemp: 30, minTemp: 22, precipitation: 0, precipitationProbability: 15, humidity: 65, weatherCode: 1, description: 'Mainly clear' },
    { date: '2026-09-08', maxTemp: 31, minTemp: 23, precipitation: 0, precipitationProbability: 10, humidity: 62, weatherCode: 0, description: 'Clear sky' },
    { date: '2026-09-09', maxTemp: 33, minTemp: 24, precipitation: 0, precipitationProbability: 5, humidity: 58, weatherCode: 0, description: 'Clear sky' },
  ],
  risks: {
    irrigationStress: 'low',
    heatStress: 'moderate',
    diseaseRisk: 'high',
    droughtRisk: 'low',
    rainfallOpportunity: true,
    sprayConditions: 'marginal',
  },
  source: 'Open-Meteo',
  fetchedAt: new Date().toISOString(),
  isDemo: true,
};

export const DEMO_SOIL: SoilProfile = {
  ph: 7.8,
  organicCarbon: 0.48,
  sand: 42,
  silt: 35,
  clay: 23,
  bulkDensity: 1.32,
  nitrogen: 0.9,
  source: 'demo',
  fetchedAt: new Date().toISOString(),
  isDemo: true,
};

export const DEMO_SATELLITE: SatelliteSnapshot = {
  farmId: DEMO_FARM_ID,
  date: new Date().toISOString().split('T')[0],
  ndvi: 0.58,
  ndviMin: 0.42,
  ndviMax: 0.71,
  ndmiAvg: 0.31,
  trend: 'stable',
  trendValue: -0.02,
  status: 'healthy',
  source: 'Sentinel-2 / Google Earth Engine',
  isDemo: true,
};

export const DEMO_ALERTS: FarmAlert[] = [
  {
    id: 'alert-001',
    farmId: DEMO_FARM_ID,
    type: 'disease_risk',
    severity: 'warning',
    title: 'Elevated Fungal Disease Risk',
    message: 'High humidity (72%) combined with moderate temperature creates favorable conditions for fungal disease. Inspect lower leaves.',
    recommendedAction: 'Inspect crop canopy tomorrow morning. Look for early fungal symptoms on lower leaves.',
    createdAt: new Date().toISOString(),
    read: false,
  },
  {
    id: 'alert-002',
    farmId: DEMO_FARM_ID,
    type: 'rainfall_deficit',
    severity: 'info',
    title: 'Rainfall Expected in 36 Hours',
    message: 'Moderate rainfall (8–12mm) forecast in 36-48 hours. Consider delaying irrigation.',
    recommendedAction: 'Delay irrigation by 24-36 hours and reassess after rainfall.',
    createdAt: new Date().toISOString(),
    read: false,
  },
];

export const DEMO_REGENERATIVE_SCORE: RegenerativeScore = {
  farmId: DEMO_FARM_ID,
  total: 71,
  label: 'AgriOS Regenerative Index',
  categories: {
    soilHealth: {
      name: 'Soil Health',
      score: 62,
      maxScore: 100,
      status: 'fair',
      explanation: 'Soil pH is slightly alkaline (7.8) and organic carbon is low (0.48 g/kg). These limit nutrient availability and soil biology.',
      improvements: ['Add composted organic matter', 'Consider cover cropping after harvest', 'Minimize bare soil periods'],
      confidence: 78,
    },
    waterEfficiency: {
      name: 'Water Efficiency',
      score: 79,
      maxScore: 100,
      status: 'good',
      explanation: 'Drip irrigation system provides good efficiency. Irrigation scheduling can be further optimized using rainfall forecasts.',
      improvements: ['Use soil moisture sensors', 'Align irrigation with forecast', 'Mulch to reduce evaporation'],
      confidence: 82,
    },
    biodiversity: {
      name: 'Biodiversity',
      score: 54,
      maxScore: 100,
      status: 'fair',
      explanation: 'Single crop wheat without rotation reduces biodiversity. No cover crop or intercrop practice detected.',
      improvements: ['Introduce crop rotation (legumes)', 'Consider cover crop after harvest', 'Maintain field margins'],
      confidence: 70,
    },
    inputEfficiency: {
      name: 'Input Efficiency',
      score: 73,
      maxScore: 100,
      status: 'good',
      explanation: 'Integrated approach to inputs. Some reduction in chemical fertilizer use possible given soil pH.',
      improvements: ['Test soil before fertilizer application', 'Use biostimulants', 'Target specific nutrient deficiencies'],
      confidence: 75,
    },
    cropResilience: {
      name: 'Crop Resilience',
      score: 76,
      maxScore: 100,
      status: 'good',
      explanation: 'Wheat variety shows reasonable tolerance. Current vegetation signal (NDVI 0.58) is within normal range.',
      improvements: ['Consider disease-resistant variety next season', 'Improve canopy management'],
      confidence: 80,
    },
    carbonOM: {
      name: 'Carbon & Organic Matter',
      score: 58,
      maxScore: 100,
      status: 'fair',
      explanation: 'Organic carbon at 0.48 g/kg is below optimal (>1.0 g/kg). Crop residue incorporation could help.',
      improvements: ['Incorporate crop residues', 'Apply compost annually', 'Avoid burning residues'],
      confidence: 72,
    },
    climateResilience: {
      name: 'Climate Resilience',
      score: 77,
      maxScore: 100,
      status: 'good',
      explanation: 'Farm has moderate climate risk. Irrigation access and weather monitoring provide resilience buffer.',
      improvements: ['Diversify crops', 'Improve drainage for heavy rain events', 'Establish wind breaks'],
      confidence: 74,
    },
  },
  scoredAt: new Date().toISOString(),
  disclaimer: 'AgriOS Regenerative Index is a composite indicator, not an official scientific certification. Scores are estimates based on available farm data.',
};

export const DEMO_AGRIMESH_NODES = [
  {
    id: 'node-india',
    country: 'India',
    countryCode: 'IN',
    nodeLabel: 'India Agricultural Intelligence Node',
    lat: 20.59,
    lng: 78.96,
    status: 'active' as const,
    contributionsCount: 48,
    contributions: [
      { type: 'disease_pattern' as const, title: 'Wheat Yellow Rust Patterns (North India)', description: 'Early-season rust detection patterns from Punjab and Haryana wheat belt', crop: 'Wheat', region: 'North India', sharedAt: new Date(Date.now() - 2 * 60000).toISOString() },
      { type: 'practice' as const, title: 'Zero-Tillage Wheat Cultivation', description: 'Water-saving zero-tillage practices adapted for Indo-Gangetic Plains', crop: 'Wheat', region: 'Indo-Gangetic Plains', sharedAt: new Date(Date.now() - 5 * 60000).toISOString() },
      { type: 'crop_model' as const, title: 'Rice Water Optimization Model v2.1', description: 'Water-efficient paddy irrigation scheduling model', crop: 'Rice', region: 'Odisha', sharedAt: new Date(Date.now() - 15 * 60000).toISOString() },
    ],
    modelVersion: 'v1.2',
    lastSync: new Date(Date.now() - 2 * 60000).toISOString(),
    isSimulated: true,
  },
  {
    id: 'node-brazil',
    country: 'Brazil',
    countryCode: 'BR',
    nodeLabel: 'Brazil AgriMesh Node',
    lat: -14.24,
    lng: -51.93,
    status: 'active' as const,
    contributionsCount: 31,
    contributions: [
      { type: 'practice' as const, title: 'Tropical Soil Regeneration Framework', description: 'Cerrado biome soil restoration practices for degraded agricultural land', crop: 'Soybean', region: 'Mato Grosso', sharedAt: new Date(Date.now() - 12 * 60000).toISOString() },
      { type: 'disease_pattern' as const, title: 'Soybean Asian Rust Early Warning', description: 'Sentinel-2 based early detection model for Asian soybean rust', crop: 'Soybean', region: 'Paraná', sharedAt: new Date(Date.now() - 30 * 60000).toISOString() },
    ],
    modelVersion: 'v1.1',
    lastSync: new Date(Date.now() - 8 * 60000).toISOString(),
    isSimulated: true,
  },
  {
    id: 'node-south-africa',
    country: 'South Africa',
    countryCode: 'ZA',
    nodeLabel: 'South Africa AgriMesh Node',
    lat: -30.56,
    lng: 22.94,
    status: 'active' as const,
    contributionsCount: 19,
    contributions: [
      { type: 'practice' as const, title: 'Drought Resilience Framework for Dryland Farming', description: 'Water-harvesting and drought-tolerance practices for Southern Africa arid zones', crop: 'Maize', region: 'Northern Cape', sharedAt: new Date(Date.now() - 18 * 60000).toISOString() },
      { type: 'climate_insight' as const, title: 'Southern Africa Seasonal Rainfall Patterns', description: 'Climate intelligence for El Niño impact on Southern African agriculture', region: 'Southern Africa', sharedAt: new Date(Date.now() - 45 * 60000).toISOString() },
    ],
    modelVersion: 'v1.0',
    lastSync: new Date(Date.now() - 15 * 60000).toISOString(),
    isSimulated: true,
  },
  {
    id: 'node-china',
    country: 'China',
    countryCode: 'CN',
    nodeLabel: 'China AgriMesh Node',
    lat: 35.86,
    lng: 104.19,
    status: 'syncing' as const,
    contributionsCount: 27,
    contributions: [
      { type: 'crop_model' as const, title: 'Rice Precision Fertilization Model', description: 'Nitrogen optimization model for paddy rice reducing fertilizer use 20%', crop: 'Rice', region: 'Yangtze Delta', sharedAt: new Date(Date.now() - 60 * 60000).toISOString() },
      { type: 'disease_pattern' as const, title: 'Wheat Blast Disease Intelligence', description: 'Rapid response patterns for wheat blast spread risk', crop: 'Wheat', region: 'Huanghuai Plain', sharedAt: new Date(Date.now() - 90 * 60000).toISOString() },
    ],
    modelVersion: 'v1.1',
    lastSync: new Date(Date.now() - 25 * 60000).toISOString(),
    isSimulated: true,
  },
  {
    id: 'node-russia',
    country: 'Russia',
    countryCode: 'RU',
    nodeLabel: 'Russia AgriMesh Node',
    lat: 61.52,
    lng: 105.32,
    status: 'active' as const,
    contributionsCount: 15,
    contributions: [
      { type: 'practice' as const, title: 'Cold-Weather Soil Protection Practices', description: 'Winter soil management to prevent freeze-thaw erosion cycles', crop: 'Wheat', region: 'Black Earth Region', sharedAt: new Date(Date.now() - 3 * 60 * 60000).toISOString() },
    ],
    modelVersion: 'v0.9',
    lastSync: new Date(Date.now() - 40 * 60000).toISOString(),
    isSimulated: true,
  },
  {
    id: 'node-uae',
    country: 'UAE',
    countryCode: 'AE',
    nodeLabel: 'UAE AgriMesh Node',
    lat: 23.42,
    lng: 53.85,
    status: 'active' as const,
    contributionsCount: 11,
    contributions: [
      { type: 'practice' as const, title: 'Desert Hydroponics Water Efficiency', description: 'Ultra-low water consumption crop production models for arid environments', region: 'Al Ain', sharedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString() },
    ],
    modelVersion: 'v0.8',
    lastSync: new Date(Date.now() - 60 * 60000).toISOString(),
    isSimulated: true,
  },
];
